// Mocks generated by Mockito 5.4.6 from annotations
// in service_platform/test/providers/bookings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:service_platform/core/models/api/booking_model.dart' as _i2;
import 'package:service_platform/core/repositories/booking_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookingModel_0 extends _i1.SmartFake implements _i2.BookingModel {
  _FakeBookingModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingRepository extends _i1.Mock implements _i3.BookingRepository {
  MockBookingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BookingModel> createBooking(
          _i2.CreateBookingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [request],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #createBooking,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);

  @override
  _i4.Future<List<_i2.BookingModel>> getMyBookings({
    int? page = 1,
    int? limit = 20,
    _i2.BookingStatus? status,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyBookings,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #role: role,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.BookingModel>>.value(<_i2.BookingModel>[]),
      ) as _i4.Future<List<_i2.BookingModel>>);

  @override
  _i4.Future<_i2.BookingModel> getBookingById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingById,
          [id],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #getBookingById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);

  @override
  _i4.Future<_i2.BookingModel> confirmBooking(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmBooking,
          [id],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #confirmBooking,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);

  @override
  _i4.Future<_i2.BookingModel> cancelBooking(
    String? id,
    _i2.CancelBookingRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelBooking,
          [
            id,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #cancelBooking,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);

  @override
  _i4.Future<_i2.BookingModel> completeBooking(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeBooking,
          [id],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #completeBooking,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);

  @override
  _i4.Future<_i2.BookingModel> updateBookingStatus(
    String? id,
    _i2.UpdateBookingStatusRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookingStatus,
          [
            id,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.BookingModel>.value(_FakeBookingModel_0(
          this,
          Invocation.method(
            #updateBookingStatus,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BookingModel>);
}
