// Mocks generated by Mockito 5.4.6 from annotations
// in service_platform/test/providers/feed_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:service_platform/core/models/api/post_model.dart' as _i2;
import 'package:service_platform/core/repositories/post_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostModel_0 extends _i1.SmartFake implements _i2.PostModel {
  _FakePostModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentModel_1 extends _i1.SmartFake implements _i2.CommentModel {
  _FakeCommentModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PostModel>> getFeed({
    int? page = 1,
    int? limit = 20,
    List<String>? categoryIds,
    double? lat,
    double? lng,
    double? radius,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeed,
          [],
          {
            #page: page,
            #limit: limit,
            #categoryIds: categoryIds,
            #lat: lat,
            #lng: lng,
            #radius: radius,
          },
        ),
        returnValue: _i4.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i4.Future<List<_i2.PostModel>>);

  @override
  _i4.Future<_i2.PostModel> getPostById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [id],
        ),
        returnValue: _i4.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #getPostById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<_i2.PostModel> createPost(_i2.CreatePostRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [request],
        ),
        returnValue: _i4.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #createPost,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<_i2.PostModel> updatePost(
    String? id,
    _i2.UpdatePostRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [
            id,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #updatePost,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<void> deletePost(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> likePost(String? id) => (super.noSuchMethod(
        Invocation.method(
          #likePost,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unlikePost(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unlikePost,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.CommentModel>> getComments(
    String? postId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.CommentModel>>.value(<_i2.CommentModel>[]),
      ) as _i4.Future<List<_i2.CommentModel>>);

  @override
  _i4.Future<String> uploadPostMedia(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #uploadPostMedia,
          [filePath],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPostMedia,
            [filePath],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.CommentModel> createComment(
    String? postId,
    _i2.CreateCommentRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [
            postId,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.CommentModel>.value(_FakeCommentModel_1(
          this,
          Invocation.method(
            #createComment,
            [
              postId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.CommentModel>);
}
