import { MigrationInterface, QueryRunner } from "typeorm";

export class InitBaseSchema1782639034802 implements MigrationInterface {
    name = 'InitBaseSchema1782639034802'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "phone" character varying(20), "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "avatar_url" text, "is_master" boolean NOT NULL DEFAULT false, "master_profile_completed" boolean NOT NULL DEFAULT false, "is_verified" boolean NOT NULL DEFAULT false, "is_premium" boolean NOT NULL DEFAULT false, "premium_until" TIMESTAMP, "is_admin" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "rating" numeric(3,2) NOT NULL DEFAULT '0', "reviews_count" integer NOT NULL DEFAULT '0', "cancellations_count" integer NOT NULL DEFAULT '0', "no_shows_count" integer NOT NULL DEFAULT '0', "blacklists_count" integer NOT NULL DEFAULT '0', "language" character varying(5) NOT NULL DEFAULT 'en', "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "last_location_lat" numeric(10,8), "last_location_lng" numeric(11,8), "posts_count" integer NOT NULL DEFAULT '0', "friends_count" integer NOT NULL DEFAULT '0', "followers_count" integer NOT NULL DEFAULT '0', "following_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c591ce0e3142dc154f8de66003" ON "users" ("is_master") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "master_id" uuid NOT NULL, "category_id" uuid NOT NULL, "subcategory_id" uuid, "service_template_id" uuid, "name" character varying(255) NOT NULL, "description" text, "price" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'RUB', "price_from" numeric(10,2), "price_to" numeric(10,2), "duration_minutes" integer NOT NULL, "is_bookable_online" boolean NOT NULL DEFAULT true, "is_mobile" boolean NOT NULL DEFAULT false, "is_in_salon" boolean NOT NULL DEFAULT true, "tags" character varying(50) array NOT NULL DEFAULT '{}', "photo_urls" text array NOT NULL DEFAULT '{}', "bookings_count" integer NOT NULL DEFAULT '0', "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93312ba8a0294112e9b55278b9" ON "services" ("service_template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_225a558e86b74142779d7066ea" ON "services" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3e126c6bf3deff2375288acbc" ON "services" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f8d1173481678a035b4a81a4e" ON "services" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e29895fa6d73dff35b55bd28c9" ON "services" ("master_id") `);
        await queryRunner.query(`CREATE TABLE "master_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "bio" text, "category_ids" uuid array NOT NULL DEFAULT '{}', "subcategory_ids" uuid array NOT NULL DEFAULT '{}', "rating" numeric(3,2) NOT NULL DEFAULT '0', "reviews_count" integer NOT NULL DEFAULT '0', "completed_bookings" integer NOT NULL DEFAULT '0', "cancellations_count" integer NOT NULL DEFAULT '0', "views_count" integer NOT NULL DEFAULT '0', "favorites_count" integer NOT NULL DEFAULT '0', "subscribers_count" integer NOT NULL DEFAULT '0', "location_lat" numeric(10,8), "location_lng" numeric(11,8), "location_address" character varying(255), "location_name" character varying(100), "service_radius_km" integer, "is_mobile" boolean NOT NULL DEFAULT false, "has_location" boolean NOT NULL DEFAULT false, "is_online_only" boolean NOT NULL DEFAULT false, "portfolio_urls" text array NOT NULL DEFAULT '{}', "video_urls" text array NOT NULL DEFAULT '{}', "social_links" jsonb, "working_hours" jsonb, "min_booking_hours" integer NOT NULL DEFAULT '2', "max_bookings_per_day" integer, "auto_confirm" boolean NOT NULL DEFAULT false, "years_of_experience" integer, "certificates" text array NOT NULL DEFAULT '{}', "languages" character varying(5) array NOT NULL DEFAULT '{ru}', "is_active" boolean NOT NULL DEFAULT true, "is_approved" boolean NOT NULL DEFAULT false, "setup_step" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_a32253451c37d3886f344f6190" UNIQUE ("user_id"), CONSTRAINT "PK_8fb52453cc50f213aae9e9228b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8dc51265a671e7f7ac2d107750" ON "master_profiles" ("category_ids") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ba8dd0a9cd121bf7a2c669fb6" ON "master_profiles" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bf04afcbff298167285376790" ON "master_profiles" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a32253451c37d3886f344f6190" ON "master_profiles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_id" uuid, "slug" character varying(100) NOT NULL, "level" integer NOT NULL DEFAULT '0', "icon_url" text, "image_url" text, "color" character varying(7), "display_order" integer NOT NULL DEFAULT '0', "masters_count" integer NOT NULL DEFAULT '0', "services_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "is_popular" boolean NOT NULL DEFAULT false, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "parentId" uuid, CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_083b4657d537e819d86961f4aa" ON "categories" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_88cea2dc9c31951d06437879b4" ON "categories" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "category_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "language" character varying(5) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "keywords" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_9dff018a4a26a924c60d3e86432" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3e1edb89dda90329749d21836a" ON "category_translations" ("category_id", "language") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6885b13b60a96fa79e0c27fe2" ON "category_translations" ("language") `);
        await queryRunner.query(`CREATE INDEX "IDX_87902f79e775e1c1b0082201d7" ON "category_translations" ("category_id") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid NOT NULL, "master_id" uuid NOT NULL, "service_id" uuid NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "duration_minutes" integer NOT NULL, "price" numeric(10,2) NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending', "comment" text, "cancellation_reason" text, "cancelled_by" uuid, "client_review_left" boolean NOT NULL DEFAULT false, "master_review_left" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP, "location_address" text, "location_lat" numeric(10,8), "location_lng" numeric(11,8), "location_type" character varying(20) NOT NULL DEFAULT 'salon', "reminder_sent" boolean NOT NULL DEFAULT false, "reminder_sent_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0badd9c969b0964ab8ebb3c1c7" ON "bookings" ("client_id", "client_review_left") `);
        await queryRunner.query(`CREATE INDEX "IDX_0012aa4109fa85fcc043e36016" ON "bookings" ("start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b267d894e32a25ebde4b207a" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_df22e2beaabc33a432b4f65e3c" ON "bookings" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0519bd387c76e48883119a4f3" ON "bookings" ("master_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23096dca2f7a9d1505d0267d4c" ON "bookings" ("client_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reviews_reviewer_type_enum" AS ENUM('client', 'master')`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL, "reviewed_user_id" uuid NOT NULL, "reviewer_type" "public"."reviews_reviewer_type_enum" NOT NULL, "rating" integer NOT NULL, "comment" text, "photo_urls" text array NOT NULL DEFAULT '{}', "response" text, "response_at" TIMESTAMP, "is_visible" boolean NOT NULL DEFAULT true, "reports_count" integer NOT NULL DEFAULT '0', "is_approved" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bbd6ac6e3e6a8f8c6e0e8692d63" UNIQUE ("booking_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4b88c05a7adf404a6e6b2f1eb" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_7158c538f468b9bbe912d6656e" ON "reviews" ("reviewer_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f46ea67dc2809872299d3a6f80" ON "reviews" ("reviewed_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92e950a2513a79bb3fab273c92" ON "reviews" ("reviewer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bbd6ac6e3e6a8f8c6e0e8692d6" ON "reviews" ("booking_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_participants_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "chat_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."chat_participants_role_enum" NOT NULL DEFAULT 'member', "last_read_message_id" uuid, "last_read_at" TIMESTAMP, "unread_count" integer NOT NULL DEFAULT '0', "notifications_enabled" boolean NOT NULL DEFAULT true, "is_archived" boolean NOT NULL DEFAULT false, "is_pinned" boolean NOT NULL DEFAULT false, "is_removed" boolean NOT NULL DEFAULT false, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_36c99e4a017767179cc49d0ac74" UNIQUE ("chat_id", "user_id"), CONSTRAINT "PK_ebf68c52a2b4dceb777672b782d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4129b3e21906ca57b503a1d83" ON "chat_participants" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9946d299e9ccfbee23aa40c554" ON "chat_participants" ("chat_id") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'photo', 'video', 'voice', 'location', 'profile_share', 'post_share', 'booking_proposal')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text', "content" text, "media_url" text, "thumbnail_url" text, "media_metadata" jsonb, "location_lat" numeric(10,8), "location_lng" numeric(11,8), "location_name" character varying(255), "shared_profile_id" uuid, "shared_post_id" uuid, "booking_proposal_id" uuid, "reply_to_id" uuid, "read_count" integer NOT NULL DEFAULT '0', "is_edited" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22133395bd13b970ccd0c34ab2" ON "messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_366ea02dc46f24c57d225cbd79" ON "messages" ("chat_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."chats_type_enum" AS ENUM('direct', 'group')`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."chats_type_enum" NOT NULL DEFAULT 'direct', "name" character varying(255), "avatar_url" text, "creator_id" uuid, "last_message_id" uuid, "last_message_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8685243ec9ac46c27a1935ea69" ON "chats" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_82098aa8bb9df492a810ff0be9" ON "chats" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."friendships_status_enum" AS ENUM('pending', 'accepted', 'declined', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "friendships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requester_id" uuid NOT NULL, "addressee_id" uuid NOT NULL, "status" "public"."friendships_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2697f4d8948008ebd0784fe79c7" UNIQUE ("requester_id", "addressee_id"), CONSTRAINT "PK_08af97d0be72942681757f07bc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a5bbd95512887c0824c8ae006" ON "friendships" ("addressee_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_65a5ecb896ed4ad0b8de79d83a" ON "friendships" ("requester_id", "status") `);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriber_id" uuid NOT NULL, "target_id" uuid NOT NULL, "notifications_enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_51082dd97cfc77bdbbe8a72c1d5" UNIQUE ("subscriber_id", "target_id"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc35212184f14aed5d53182373" ON "subscriptions" ("target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f56b7683178d56b3907fea7248" ON "subscriptions" ("subscriber_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('booking_created', 'booking_confirmed', 'booking_rejected', 'booking_cancelled', 'booking_started', 'booking_completed', 'booking_reminder', 'review_received', 'review_response', 'review_reminder', 'new_message', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "related_id" uuid, "related_type" character varying(50), "metadata" jsonb, "action_url" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af08fad7c04bb85403970afdc1" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_platform_enum" AS ENUM('android', 'ios')`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" text NOT NULL, "platform" "public"."device_tokens_platform_enum" NOT NULL, "device_model" character varying(100), "os_version" character varying(50), "app_version" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "last_used_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_977e24c520c49436d08e5eeea8a" UNIQUE ("token"), CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_977e24c520c49436d08e5eeea8" ON "device_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_17e1f528b993c6d55def4cf5be" ON "device_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."post_media_type_enum" AS ENUM('photo', 'video')`);
        await queryRunner.query(`CREATE TABLE "post_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "type" "public"."post_media_type_enum" NOT NULL, "url" text NOT NULL, "thumbnail_url" text, "order" integer NOT NULL DEFAULT '0', "width" integer, "height" integer, "duration" integer, CONSTRAINT "PK_049edb1ce7ab3d2a98009b171d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1eeb54a4fdfbe9db17899243cb" ON "post_media" ("post_id") `);
        await queryRunner.query(`CREATE TABLE "post_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "service_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fce78231966cf1bea06c5e8f373" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_01e01d2cc5e33f904bb4eeb42a" ON "post_services" ("post_id", "service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_84f4c23ad044faecdb223d528b" ON "post_services" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0203582fdaf7e3a7dc1417e31f" ON "post_services" ("post_id") `);
        await queryRunner.query(`CREATE TYPE "public"."posts_type_enum" AS ENUM('text', 'photo', 'video', 'repost')`);
        await queryRunner.query(`CREATE TYPE "public"."posts_privacy_enum" AS ENUM('public', 'friends', 'private')`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_id" uuid NOT NULL, "type" "public"."posts_type_enum" NOT NULL DEFAULT 'text', "content" text, "privacy" "public"."posts_privacy_enum" NOT NULL DEFAULT 'public', "repost_of_id" uuid, "likes_count" integer NOT NULL DEFAULT '0', "comments_count" integer NOT NULL DEFAULT '0', "reposts_count" integer NOT NULL DEFAULT '0', "views_count" integer NOT NULL DEFAULT '0', "location_lat" numeric(10,8), "location_lng" numeric(11,8), "location_name" character varying(255), "custom_service_name" text, "category_ids" uuid array NOT NULL DEFAULT '{}', "comments_disabled" boolean NOT NULL DEFAULT false, "is_pinned" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d62fd5b96a11fa295c9d6f469" ON "posts" ("category_ids") `);
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b2fdcb4fb94d189e0e679748a" ON "posts" ("author_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."likes_likable_type_enum" AS ENUM('post', 'comment')`);
        await queryRunner.query(`CREATE TABLE "likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "likable_type" "public"."likes_likable_type_enum" NOT NULL, "likable_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d2ccde745e53b5c79d9c66a1c94" UNIQUE ("user_id", "likable_type", "likable_id"), CONSTRAINT "PK_a9323de3f8bced7539a794b4a37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f519ed95f775c781a25408917" ON "likes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd81c0e479e58f440cc6970463" ON "likes" ("likable_type", "likable_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "author_id" uuid NOT NULL, "content" text NOT NULL, "parent_comment_id" uuid, "likes_count" integer NOT NULL DEFAULT '0', "replies_count" integer NOT NULL DEFAULT '0', "is_edited" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93ce08bdbea73c0c7ee673ec35" ON "comments" ("parent_comment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d38899c31997c45d128a8973" ON "comments" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a1038b5b8f236c9ddb068af5" ON "comments" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "reposts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "post_id" uuid NOT NULL, "comment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46eae4fae363dd5d5626035b5ab" UNIQUE ("user_id", "post_id"), CONSTRAINT "PK_52695faa15b7c703f8660581f81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0900495dc74309d70b02464e" ON "reposts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e26caf3c8bcca49a9acbdf0715" ON "reposts" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."auto_proposals_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "auto_proposals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "master_id" uuid NOT NULL, "service_id" uuid NOT NULL, "category_id" uuid NOT NULL, "status" "public"."auto_proposals_status_enum" NOT NULL DEFAULT 'pending', "match_score" integer NOT NULL DEFAULT '0', "match_reasons" jsonb, "proposed_datetime" TIMESTAMP, "expires_at" TIMESTAMP NOT NULL, "booking_id" uuid, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1c4da4a4525046283560afb2f1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f7ac385a4473a19843af346ef" ON "auto_proposals" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ba5d849af31b1a4719637d820" ON "auto_proposals" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a527bb6104fcf5d348895e42d" ON "auto_proposals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b1e5fb86ac3591b0af0764892" ON "auto_proposals" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "auto_proposal_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "is_enabled" boolean NOT NULL DEFAULT true, "interval_days" integer NOT NULL DEFAULT '7', "preferred_categories" jsonb, "max_price" numeric(10,2), "max_distance_km" integer NOT NULL DEFAULT '10', "min_rating" numeric(2,1) NOT NULL DEFAULT '4', "preferred_time_slots" jsonb, "last_proposal_at" TIMESTAMP, "next_proposal_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_da5901f86edf305bffdb4f7ae29" UNIQUE ("user_id"), CONSTRAINT "PK_1797e67f7c23e0d2ae9eb3a37bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da5901f86edf305bffdb4f7ae2" ON "auto_proposal_settings" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."favorites_entity_type_enum" AS ENUM('master', 'post')`);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "entity_type" "public"."favorites_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c783677adbb9e96c9ac85cdae3" ON "favorites" ("user_id", "entity_id", "entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_74fe0518ced56e1c656af977b8" ON "favorites" ("user_id", "entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e5067842c383aa684e5a510f8" ON "favorites" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_35a6b05ee3b624d0de01ee5059" ON "favorites" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "service_template_translations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service_template_id" uuid NOT NULL, "language" character varying(10) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "keywords" character varying(50) array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_00fb8847034bd24843233832371" UNIQUE ("service_template_id", "language"), CONSTRAINT "PK_079a75cc4abd9e3b0825a023ae6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f9670eb25bce69d9fb796c82b" ON "service_template_translations" ("language") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4fccf9c3e7b1d2b92168ddbf0" ON "service_template_translations" ("service_template_id") `);
        await queryRunner.query(`CREATE TABLE "service_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "slug" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "icon_url" text, "default_duration_minutes" integer, "default_price_range_min" numeric(10,2), "default_price_range_max" numeric(10,2), "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_01b7efb49a948df8563d56ce8e5" UNIQUE ("slug"), CONSTRAINT "PK_97bdd13baebd4bd3723aa0d3076" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_01b7efb49a948df8563d56ce8e" ON "service_templates" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_1adef892d85ed081208e3f117d" ON "service_templates" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4935298c1681fe45f7a5a2a11" ON "service_templates" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "categories_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_dc67f6a82852c15ec6e4243398d" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ea1e9c4eea91160dfdb4318778" ON "categories_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_51fff5114cc41723e8ca36cf22" ON "categories_closure" ("id_descendant") `);
        // NOTE: убран мусорный блок DROP/ADD PRIMARY KEY для "post_services",
        // сгенерированный из-за двойного маппинга таблицы в Post entity
        // (@OneToMany(PostService) + @ManyToMany+@JoinTable). Таблица уже создана
        // выше с корректным PK("id") и unique-индексом (post_id, service_id).
        await queryRunner.query(`ALTER TABLE "master_profiles" ADD CONSTRAINT "FK_a32253451c37d3886f344f61904" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_23096dca2f7a9d1505d0267d4c6" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_a0519bd387c76e48883119a4f35" FOREIGN KEY ("master_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_df22e2beaabc33a432b4f65e3c2" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_9946d299e9ccfbee23aa40c5545" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_b4129b3e21906ca57b503a1d834" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7540635fef1922f0b156b9ef74f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_54e66104dd534ed1c191e44096f" FOREIGN KEY ("reply_to_id") REFERENCES "messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_4cf3c68ed4a5a9fde8d4c2b7319" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_01b0760fd2402d21f12c6dc5f89" FOREIGN KEY ("addressee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_f56b7683178d56b3907fea72489" FOREIGN KEY ("subscriber_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_dc35212184f14aed5d53182373c" FOREIGN KEY ("target_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_media" ADD CONSTRAINT "FK_1eeb54a4fdfbe9db17899243cbe" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "FK_0203582fdaf7e3a7dc1417e31fd" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "FK_84f4c23ad044faecdb223d528b9" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_312c63be865c81b922e39c2475e" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_80c1fd1d3486440b51279293381" FOREIGN KEY ("repost_of_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_3f519ed95f775c781a254089171" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a" FOREIGN KEY ("parent_comment_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reposts" ADD CONSTRAINT "FK_3d0900495dc74309d70b02464e2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reposts" ADD CONSTRAINT "FK_70d9186444e242f48c3fce21770" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_template_translations" ADD CONSTRAINT "FK_d4fccf9c3e7b1d2b92168ddbf0a" FOREIGN KEY ("service_template_id") REFERENCES "service_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_templates" ADD CONSTRAINT "FK_b4935298c1681fe45f7a5a2a118" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories_closure" ADD CONSTRAINT "FK_ea1e9c4eea91160dfdb4318778d" FOREIGN KEY ("id_ancestor") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories_closure" ADD CONSTRAINT "FK_51fff5114cc41723e8ca36cf227" FOREIGN KEY ("id_descendant") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "categories_closure" DROP CONSTRAINT "FK_51fff5114cc41723e8ca36cf227"`);
        await queryRunner.query(`ALTER TABLE "categories_closure" DROP CONSTRAINT "FK_ea1e9c4eea91160dfdb4318778d"`);
        await queryRunner.query(`ALTER TABLE "service_templates" DROP CONSTRAINT "FK_b4935298c1681fe45f7a5a2a118"`);
        await queryRunner.query(`ALTER TABLE "service_template_translations" DROP CONSTRAINT "FK_d4fccf9c3e7b1d2b92168ddbf0a"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "reposts" DROP CONSTRAINT "FK_70d9186444e242f48c3fce21770"`);
        await queryRunner.query(`ALTER TABLE "reposts" DROP CONSTRAINT "FK_3d0900495dc74309d70b02464e2"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_3f519ed95f775c781a254089171"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_80c1fd1d3486440b51279293381"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_312c63be865c81b922e39c2475e"`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "FK_84f4c23ad044faecdb223d528b9"`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "FK_0203582fdaf7e3a7dc1417e31fd"`);
        await queryRunner.query(`ALTER TABLE "post_media" DROP CONSTRAINT "FK_1eeb54a4fdfbe9db17899243cbe"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_dc35212184f14aed5d53182373c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_f56b7683178d56b3907fea72489"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_01b0760fd2402d21f12c6dc5f89"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_4cf3c68ed4a5a9fde8d4c2b7319"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_54e66104dd534ed1c191e44096f"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7540635fef1922f0b156b9ef74f"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_b4129b3e21906ca57b503a1d834"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_9946d299e9ccfbee23aa40c5545"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_df22e2beaabc33a432b4f65e3c2"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_a0519bd387c76e48883119a4f35"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_23096dca2f7a9d1505d0267d4c6"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "master_profiles" DROP CONSTRAINT "FK_a32253451c37d3886f344f61904"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01e01d2cc5e33f904bb4eeb42a"`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_3184d284ea92ff3c28082ba394a"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_708a24c4d7713dca5463d29de77" PRIMARY KEY ("post_id", "id")`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_708a24c4d7713dca5463d29de77"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_fce78231966cf1bea06c5e8f373" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_fce78231966cf1bea06c5e8f373"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_77dbf4959d5350b4b3f4ed9f525" PRIMARY KEY ("service_id", "id")`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_77dbf4959d5350b4b3f4ed9f525"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_3184d284ea92ff3c28082ba394a" PRIMARY KEY ("post_id", "service_id", "id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_01e01d2cc5e33f904bb4eeb42a" ON "post_services" ("post_id", "service_id") `);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_01e01d2cc5e33f904bb4eeb42a6"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_fce78231966cf1bea06c5e8f373" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP CONSTRAINT "PK_fce78231966cf1bea06c5e8f373"`);
        await queryRunner.query(`ALTER TABLE "post_services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_services" ADD CONSTRAINT "PK_fce78231966cf1bea06c5e8f373" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51fff5114cc41723e8ca36cf22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1e9c4eea91160dfdb4318778"`);
        await queryRunner.query(`DROP TABLE "categories_closure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4935298c1681fe45f7a5a2a11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1adef892d85ed081208e3f117d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01b7efb49a948df8563d56ce8e"`);
        await queryRunner.query(`DROP TABLE "service_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4fccf9c3e7b1d2b92168ddbf0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f9670eb25bce69d9fb796c82b"`);
        await queryRunner.query(`DROP TABLE "service_template_translations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a6b05ee3b624d0de01ee5059"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e5067842c383aa684e5a510f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74fe0518ced56e1c656af977b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c783677adbb9e96c9ac85cdae3"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP TYPE "public"."favorites_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da5901f86edf305bffdb4f7ae2"`);
        await queryRunner.query(`DROP TABLE "auto_proposal_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1e5fb86ac3591b0af0764892"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a527bb6104fcf5d348895e42d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ba5d849af31b1a4719637d820"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f7ac385a4473a19843af346ef"`);
        await queryRunner.query(`DROP TABLE "auto_proposals"`);
        await queryRunner.query(`DROP TYPE "public"."auto_proposals_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e26caf3c8bcca49a9acbdf0715"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0900495dc74309d70b02464e"`);
        await queryRunner.query(`DROP TABLE "reposts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a1038b5b8f236c9ddb068af5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d38899c31997c45d128a8973"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93ce08bdbea73c0c7ee673ec35"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd81c0e479e58f440cc6970463"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f519ed95f775c781a25408917"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`DROP TYPE "public"."likes_likable_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b2fdcb4fb94d189e0e679748a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60818528127866f5002e7f826d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_560752d45d78a3332853345e32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d62fd5b96a11fa295c9d6f469"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TYPE "public"."posts_privacy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."posts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0203582fdaf7e3a7dc1417e31f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84f4c23ad044faecdb223d528b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01e01d2cc5e33f904bb4eeb42a"`);
        await queryRunner.query(`DROP TABLE "post_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1eeb54a4fdfbe9db17899243cb"`);
        await queryRunner.query(`DROP TABLE "post_media"`);
        await queryRunner.query(`DROP TYPE "public"."post_media_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17e1f528b993c6d55def4cf5be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_977e24c520c49436d08e5eeea8"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af08fad7c04bb85403970afdc1"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f56b7683178d56b3907fea7248"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc35212184f14aed5d53182373"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65a5ecb896ed4ad0b8de79d83a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a5bbd95512887c0824c8ae006"`);
        await queryRunner.query(`DROP TABLE "friendships"`);
        await queryRunner.query(`DROP TYPE "public"."friendships_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82098aa8bb9df492a810ff0be9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8685243ec9ac46c27a1935ea69"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TYPE "public"."chats_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_366ea02dc46f24c57d225cbd79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22133395bd13b970ccd0c34ab2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9946d299e9ccfbee23aa40c554"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4129b3e21906ca57b503a1d83"`);
        await queryRunner.query(`DROP TABLE "chat_participants"`);
        await queryRunner.query(`DROP TYPE "public"."chat_participants_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbd6ac6e3e6a8f8c6e0e8692d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92e950a2513a79bb3fab273c92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f46ea67dc2809872299d3a6f80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7158c538f468b9bbe912d6656e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4b88c05a7adf404a6e6b2f1eb"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TYPE "public"."reviews_reviewer_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23096dca2f7a9d1505d0267d4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0519bd387c76e48883119a4f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df22e2beaabc33a432b4f65e3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b267d894e32a25ebde4b207a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0012aa4109fa85fcc043e36016"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0badd9c969b0964ab8ebb3c1c7"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87902f79e775e1c1b0082201d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6885b13b60a96fa79e0c27fe2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e1edb89dda90329749d21836a"`);
        await queryRunner.query(`DROP TABLE "category_translations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88cea2dc9c31951d06437879b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_083b4657d537e819d86961f4aa"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a32253451c37d3886f344f6190"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bf04afcbff298167285376790"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ba8dd0a9cd121bf7a2c669fb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dc51265a671e7f7ac2d107750"`);
        await queryRunner.query(`DROP TABLE "master_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e29895fa6d73dff35b55bd28c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f8d1173481678a035b4a81a4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3e126c6bf3deff2375288acbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_225a558e86b74142779d7066ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93312ba8a0294112e9b55278b9"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c591ce0e3142dc154f8de66003"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
